const test = require('node:test')
const assert = require('node:assert/strict')
const ExcelJS = require('exceljs')
const { parseQuoteSheet, extractQuoteImages } = require('./quoteWorkbook')

test('parses the quotation Sheet1 into stable products, SKUs and CNY prices', async () => {
  const workbook = new ExcelJS.Workbook()
  const sheet = workbook.addWorksheet('Sheet1')
  sheet.addRow(['产品名称', '产品图', '价格'])
  sheet.addRow(['隔热涂料200ml(10平方）', null, 260])
  sheet.addRow(['检测仪', null, '470/个'])
  const result = parseQuoteSheet(workbook, 'quote.xlsx')
  assert.equal(result.accepted, true)
  assert.equal(result.products.length, 2)
  assert.equal(result.skus[0].coverageMinSqm, 10)
  assert.equal(result.skus[0].coverageMaxSqm, 10)
  assert.equal(result.priceRules[1].unitPrice, 470)
  assert.equal(result.priceRules[0].currency, 'CNY')
  assert.equal(result.products[0].productCode, parseQuoteSheet(workbook, 'quote.xlsx').products[0].productCode)
})

test('extracts embedded images and associates them with quotation rows', async () => {
  const workbook = new ExcelJS.Workbook()
  const sheet = workbook.addWorksheet('Sheet1')
  sheet.addRow(['产品名称', '产品图', '价格'])
  sheet.addRow(['产品 A', null, 100])
  const imageId = workbook.addImage({ base64: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', extension: 'png' })
  sheet.addImage(imageId, { tl: { col: 1, row: 1 }, br: { col: 2, row: 2 } })
  const parsed = parseQuoteSheet(workbook, 'quote.xlsx')
  const images = extractQuoteImages(workbook, parsed.imageAssets)
  assert.equal(images.length, 1)
  assert.equal(images[0].productCode, parsed.products[0].productCode)
  assert.ok(images[0].buffer.length > 0)
})
